# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-30 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=b'ID')),
                ('event', models.CharField(blank=True, max_length=16, null=True)),
                ('username', models.CharField(max_length=255, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('superuser', models.NullBooleanField()),
                ('staff', models.NullBooleanField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('resource_type', models.CharField(blank=True, max_length=32, null=True)),
                ('resource_uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-datetime'],
                'verbose_name': 'audit event',
                'verbose_name_plural': 'audit events',
            },
        ),
    ]
